### ISSUE TITLE
Linux Firefox doesn't save zip

### ISSUE THREAD

**Issue by SuwiEtch** [Xwilarg/NHentaiDownloader#20] opened 2021-09-12 19:17 UTC
When the files finish downloading and zipping on 2.0.0, Firefox on linux dosen't save zip file.There are no zip files from this extension in /home/username/Downloads

**Comment by Xwilarg** [comment] 2021-09-12 19:55
Thanks for your bug report, I was able to reproduce the bug on Windows
I'll investigate the issue and keep you in touch if I manage to fix it

**Comment by Xwilarg** [comment] 2022-04-13 18:19
The issue should now be fixed, please tell me if it works for you
https://github.com/Xwilarg/NHentaiDownloader/releases/tag/v2.1.4

**Comment by Xwilarg** [comment] 2022-04-20 14:38
Closing this since the issue is fixed since 7 days, feel free to reopen if needed

**Comment by s5706820** [comment] 2022-04-30 03:43
I don't sure if i should reopen this or start a new one. but i think it's related to this one.
I Try using The extension version 2.1.5  on older version Firefox  (window) //dont sure which version// 
it still didnt save zip , --- same as the open topic---

so then I update the firefox to newest version (99.0.1) of 12 april 2022 released
after that the extension show the error message when i try to download any doujin

"An unexpected error occured (Code 503: Service Unavailable)"
^
^
this is the message.

this  message also show on EDGE Version 101.0.1210.32
//i dont know if it suppose to actutally work on EDGE tho. But I didnot use chrome so im just mention it here. 

![2022-04-30 (1)](https://user-images.githubusercontent.com/15662227/166089226-2421200d-2d59-4733-8bfc-2f0a78002ea5.png)
![2022-04-30](https://user-images.githubusercontent.com/15662227/166089227-b3bbad2b-98ec-4c78-8ac9-74d19c810462.png)

**Comment by Xwilarg** [comment] 2022-04-30 06:17
Hey, is the error only on a specific doujin or for all of them?

**Comment by Xwilarg** [comment] 2022-04-30 06:27
On a side note, I was able to successfully able to download from Firefox and Edge, are you using a third-party tool or website to access NHentai?

**Comment by s5706820** [comment] 2022-04-30 07:27
> Hey, is the error only on a specific doujin or for all of them?

So far, it is for all doujin when open in edge.
In firefox, it’s now working fine after i change the internet service.



> On a side note, I was able to successfully able to download from Firefox and Edge, are you using a third-party tool or website to access NHentai?

No. I didn’t use any 3rd-party/VPN to access Nhentai

ps. another issue, just wanna ask if the extension can working in background ? (In firefox) for now, it seem that when i move to do something and make the extension pop-up faded. It seem to stop all it process either download or zipping.
The download part is fine since it seem to still be in the local storage, but i have to redo the zipping again and again when I accidentally click something _(:3」z)_
Just want to make sure that it working this way or it’s a bug.

**Comment by Xwilarg** [comment] 2022-04-30 08:12
When are you getting the 503 error exactly? When downloading the file at the end?

The popup thing is indeed a Firefox issue, I opened #41 for it

**Comment by s5706820** [comment] 2022-04-30 09:39
> When are you getting the 503 error exactly? When downloading the file at the end?

Immediately after click download button. It not download at all


> 
> The popup thing is indeed a Firefox issue, I opened #41 for it

okay thx sir

**Comment by Xwilarg** [comment] 2022-04-30 10:39
One of the other service I use is having 503 errors with the API too, not sure why this is happening and why I can't reproduce it locally, I'll try to investigate that and come back to you if I find something

**Comment by s5706820** [comment] 2022-04-30 12:43
Okay sir
Thank for your hardwork

**Comment by Xwilarg** [comment] 2022-05-04 09:11
Hi again, for now you should be able to fix that in the options by changing the requests from API to HTML

**Closed** 2022-05-24 11:35 UTC
Labels: bug, help wanted, firefox
