### ISSUE TITLE
Can't find the downloaded files (Windows)

### ISSUE THREAD

**Issue by meatball-san** [Xwilarg/NHentaiDownloader#26] opened 2021-09-16 03:13 UTC
**Firefox Version Windows 10**
When it downloads the files, it says download complete. But when I go to check "downloads", it shows nothing; as if it never downloaded the file.

**Comment by Xwilarg** [comment] 2021-09-16 07:25
Related to #20 

Somehow ZIP download is broken on Firefox, I identified the issue in the code but I'm not sure how to fix it yet, I'll keep you updated if I manage to solve it

**Comment by Xwilarg** [comment] 2022-04-13 18:20
The issue should now be fixed, please tell me if it works for you
https://github.com/Xwilarg/NHentaiDownloader/releases/tag/v2.1.4

**Comment by Xwilarg** [comment] 2022-04-20 14:38
Closing this since the issue is fixed since 7 days, feel free to reopen if needed

**Closed by Xwilarg** 2022-04-20 14:38 UTC
Labels: bug, duplicate, firefox
