### ISSUE TITLE
Doesn't work with Vivaldi browser

### ISSUE THREAD

**Issue by holy-krist7** [Xwilarg/NHentaiDownloader#6] opened 2021-03-06 03:14 UTC
When the files finish downloading and zipping, Vivaldi crashes and the zip isn't saved

Vivaldi 3.6.2165.40 (Stable channel) (64-bit)

1. on the top left of Vivaldi browser, click on the Vivaldi logo and go to Tools>Extensions 
2. Install like you would on Chrome
3. Download any doujin from nhentai.net 

Using Chrome on the same computer, it works perfectly. I tested it on another computer as well, and Vivaldi still crashed every time.

**Comment by Xwilarg** [comment] 2021-03-06 10:54
Thanks for the bug report, I was able to reproduce it and see where it happens in the code, however I'm not exactly sure why
I'll keep you updated when I'll have more information

**Comment by Xwilarg** [comment] 2021-09-07 00:43
Hey it's been a long time but I went back to check this issue after [releasing version 2.0.0](https://github.com/Xwilarg/NHentaiDownloader/releases/tag/v2.0.0) (using Vivaldi 4.1) and it seems to work fine

Could you please confirm me if the issue is fixed on your side?

**Comment by Xwilarg** [comment] 2021-09-13 16:03
(Closing the issue, feel free to reopen it again if the issue persist)

**Closed by Xwilarg** 2021-09-13 16:03 UTC
Labels: bug
