### ISSUE TITLE
Title when enabling "Download each file separately"

### ISSUE THREAD

**Issue by MilitaryStingray** [Xwilarg/NHentaiDownloader#50] opened 2022-11-05 08:17 UTC
**Is your feature request related to a problem? Please describe.**
As of now, when enabling "Download each file separately" from the favorites tab, the file name is "favorites(page_number)(entry_number).zip" 

**Describe the solution you'd like**
The downloader should have the name of the individualized zip file be the same as the title like it is after you unzip

**Comment by Xwilarg** [comment] 2022-11-06 00:42
Thanks for reporting this issue, this should be fixed with the version 2.1.7: https://github.com/Xwilarg/NHentaiDownloader/releases/tag/v2.1.7

**Comment by Xwilarg** [comment] 2022-11-14 19:28
I'm closing this since the issue is solved since 7 days, feel free to reopen it if needed

**Closed by Xwilarg** 2022-11-14 19:28 UTC
Labels: enhancement
